import{INTELLIGENCE_STORAGE_KEYS}from"../config/one-intelligence.js";
import{DEMO_SUGGESTIONS,IntelligenceMemoryStore,OneIntelligenceEngine,SuggestionFeedbackEngine,safeSuggestionAnalytics}from"./one-intelligence.js";
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const readJson=(storage,key,fallback)=>{try{return JSON.parse(storage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
export function mountSuggestionCard({container,language="en",onPrepare=()=>{},track=()=>false,storage=localStorage,session=sessionStorage}={}){
  if(!container)return()=>{};
  const store=new IntelligenceMemoryStore(storage),engine=new OneIntelligenceEngine(),feedbackEngine=new SuggestionFeedbackEngine(),settings=store.loadSettings(),started=Date.now();
  let currentLanguage=language,feedback=readJson(storage,INTELLIGENCE_STORAGE_KEYS.feedback,[]),sessionState=readJson(session,INTELLIGENCE_STORAGE_KEYS.session,{dismissed:[],refreshes:0}),current=null;
  const record=action=>{feedback=feedbackEngine.record(current,action,feedback);storage.setItem(INTELLIGENCE_STORAGE_KEYS.feedback,JSON.stringify(feedback));track(`suggestion_${action.toLowerCase()}`,safeSuggestionAnalytics(current,action,Date.now()-started));};
  const render=()=>{const result=engine.suggest({settings,feedback,candidates:DEMO_SUGGESTIONS.filter(item=>!sessionState.dismissed.includes(item.suggestionId))});current=result.suggestion;if(!current){container.hidden=true;container.replaceChildren();return}const text=current.title[currentLanguage]||current.title.en,reason=current.reason[currentLanguage]||current.reason.en,ko=currentLanguage==="ko";container.hidden=false;container.innerHTML=`<span class="one-suggestion-text">${escapeHtml(text)}</span><details class="one-suggestion-why"><summary>${ko?"왜 이 제안인가요?":"Why this?"}</summary><p>${escapeHtml(reason)} <small>${ko?"데모 정보":"Demo context"}</small></p></details><span class="one-suggestion-actions"><button type="button" data-suggestion-accept aria-label="${ko?"제안 준비":"Accept suggestion"}" title="${ko?"이 미션 준비":"Prepare this mission"}">✓</button><button type="button" data-suggestion-dismiss aria-label="${ko?"제안 닫기":"Dismiss suggestion"}">×</button></span>`;track("suggestion_displayed",safeSuggestionAnalytics(current,"displayed"));container.querySelector("[data-suggestion-accept]")?.addEventListener("click",()=>{record("ACCEPTED");container.dataset.state="accepted";onPrepare(current.shortPrompt[currentLanguage]||current.shortPrompt.en,current)});container.querySelector("[data-suggestion-dismiss]")?.addEventListener("click",()=>{record("DISMISSED");sessionState={dismissed:[...sessionState.dismissed,current.suggestionId],refreshes:sessionState.refreshes+1};session.setItem(INTELLIGENCE_STORAGE_KEYS.session,JSON.stringify(sessionState));container.dataset.state="dismissed";if(sessionState.refreshes<=1)setTimeout(render,180);else container.hidden=true});};
  const languageListener=event=>{currentLanguage=event.detail?.language==="ko"?"ko":"en";render()};
  document.addEventListener("kastiz:language-changed",languageListener);
  try{render()}catch{container.hidden=true}
  return()=>{document.removeEventListener("kastiz:language-changed",languageListener);if(current&&!sessionState.dismissed.includes(current.suggestionId))record("IGNORED")};
}
