import{INTELLIGENCE_STORAGE_KEYS}from"../config/one-intelligence.js";
import{DEMO_SUGGESTIONS,IntelligenceMemoryStore,OneIntelligenceEngine,SuggestionFeedbackEngine,safeSuggestionAnalytics}from"./one-intelligence.js";
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const readJson=(storage,key,fallback)=>{try{return JSON.parse(storage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
const spanishSuggestions={"demo-family-dining":["¿Preparamos una idea diferente para la cena familiar de este fin de semana?","Una cocina diferente puede aportar variedad y mantener un plan cómodo para la familia.","Prepara una idea de cena japonesa en familia."],"demo-presentation":["¿Continuamos con el guion de tu presentación?","Una misión de presentación de demostración sigue sin terminar.","Continúa preparando el guion de mi presentación."],"demo-email":["¿Quieres que ONE prepare el correo de seguimiento?","Mencionaste un correo anteriormente; no hay estado de envío disponible.","Prepara un borrador de correo de seguimiento."],"demo-church-weather":["Se estima lluvia en tu ruta guardada. ¿Preparamos una revisión?","Usa una rutina de demostración y clima estimado, no tu ubicación en vivo.","Prepara una ruta considerando el clima."],"demo-family-coordination":["¿Preparamos un único plan familiar para el sábado?","Hay disponibilidad compartida en este espacio de demostración con consentimiento.","Prepara un plan familiar compartido para el sábado."],"demo-travel-followup":["¿Seguimos revisando tu viaje guardado a Madrid?","El itinerario de demostración aún no llegó a la revisión de aprobación.","Continúa revisando mi viaje a Madrid."],"demo-school-support":["¿Preparamos la lista escolar de esta semana?","Solo usa un horario escolar de demostración aprobado.","Prepara la lista escolar de esta semana."],"demo-weather-adjustment":["¿Te ayudaría una alternativa interior por la lluvia estimada?","El pronóstico es estimado y se comprobará de nuevo antes de la revisión.","Prepara una alternativa interior para mi plan."],"demo-mission-completion":["¿Revisamos la lista final de tu misión guardada?","La preparación de demostración está completa; todavía se requiere aprobación.","Abre la lista final de la misión."]};
export function mountSuggestionCard({container,language="en",onPrepare=()=>{},track=()=>false,storage=localStorage,session=sessionStorage}={}){
  if(!container)return()=>{};
  const store=new IntelligenceMemoryStore(storage),engine=new OneIntelligenceEngine(),feedbackEngine=new SuggestionFeedbackEngine(),settings=store.loadSettings(),started=Date.now();
  let currentLanguage=language,feedback=readJson(storage,INTELLIGENCE_STORAGE_KEYS.feedback,[]),sessionState=readJson(session,INTELLIGENCE_STORAGE_KEYS.session,{dismissed:[],refreshes:0}),current=null;
  const record=action=>{feedback=feedbackEngine.record(current,action,feedback);storage.setItem(INTELLIGENCE_STORAGE_KEYS.feedback,JSON.stringify(feedback));track(`suggestion_${action.toLowerCase()}`,safeSuggestionAnalytics(current,action,Date.now()-started));};
  const render=()=>{const result=engine.suggest({settings,feedback,candidates:DEMO_SUGGESTIONS.filter(item=>!sessionState.dismissed.includes(item.suggestionId))});current=result.suggestion;if(!current){container.hidden=true;container.replaceChildren();return}const es=spanishSuggestions[current.suggestionId],ko=currentLanguage==="ko",spanish=currentLanguage==="es",text=spanish&&es?es[0]:current.title[currentLanguage]||current.title.en,reason=spanish&&es?es[1]:current.reason[currentLanguage]||current.reason.en,prompt=spanish&&es?es[2]:current.shortPrompt[currentLanguage]||current.shortPrompt.en;container.hidden=false;container.innerHTML=`<span class="one-suggestion-text">${escapeHtml(text)}</span><details class="one-suggestion-why"><summary>${ko?"왜 이 제안인가요?":spanish?"¿Por qué esta sugerencia?":"Why this?"}</summary><p>${escapeHtml(reason)} <small>${ko?"데모 정보":spanish?"Contexto de demostración":"Demo context"}</small></p></details><span class="one-suggestion-actions"><button type="button" data-suggestion-accept aria-label="${ko?"제안 준비":spanish?"Preparar sugerencia":"Accept suggestion"}" title="${ko?"이 미션 준비":spanish?"Preparar esta misión":"Prepare this mission"}">✓</button><button type="button" data-suggestion-dismiss aria-label="${ko?"제안 닫기":spanish?"Cerrar sugerencia":"Dismiss suggestion"}">×</button></span>`;track("suggestion_displayed",safeSuggestionAnalytics(current,"displayed"));container.querySelector("[data-suggestion-accept]")?.addEventListener("click",()=>{record("ACCEPTED");container.dataset.state="accepted";onPrepare(prompt,current)});container.querySelector("[data-suggestion-dismiss]")?.addEventListener("click",()=>{record("DISMISSED");sessionState={dismissed:[...sessionState.dismissed,current.suggestionId],refreshes:sessionState.refreshes+1};session.setItem(INTELLIGENCE_STORAGE_KEYS.session,JSON.stringify(sessionState));container.dataset.state="dismissed";if(sessionState.refreshes<=1)setTimeout(render,180);else container.hidden=true});};
  const languageListener=event=>{currentLanguage=["en","ko","es"].includes(event.detail?.language)?event.detail.language:"en";render()};
  document.addEventListener("kastiz:language-changed",languageListener);
  try{render()}catch{container.hidden=true}
  return()=>{document.removeEventListener("kastiz:language-changed",languageListener);if(current&&!sessionState.dismissed.includes(current.suggestionId))record("IGNORED")};
}
