import{BILLING_EXECUTION_ENABLED,COIN_POLICY,ENTITLEMENT_KEYS,PERMISSION_KEYS,PURCHASES_ENABLED,ROLE_KEYS,SUBSCRIPTION_CATALOG,TIER_KEYS,TRANSFERS_ENABLED,WALLET_TYPES,configureSubscriptionCatalog}from"../config/mission-economy.js";

export const FREE_ACTIONS=Object.freeze(["search","classify","plan","edit","refine","retry","change_destination","change_provider","change_budget","change_dates","change_participants","change_transportation","rebuild_itinerary","review"]);
export const MISSION_STATES=Object.freeze(["MISSION_CREATED","CLASSIFYING","PLANNING","EDITING","PREPARING","ONE_READY","WAITING_FOR_APPROVAL","APPROVED_FOR_DEMO","READY_FOR_COMPLETION","USER_CONFIRMED_COMPLETE","MISSION_COMPLETED","MISSION_PAUSED","MISSION_CANCELLED","MISSION_REOPENED","MISSION_FAILED","MISSION_ARCHIVED"]);
export const CHARGEABLE_EVENT="MISSION_COMPLETION_DEBIT";
export const LEDGER_TRANSACTION_TYPES=Object.freeze(["MONTHLY_ALLOCATION","MISSION_COMPLETION_DEBIT","PURCHASED_COIN_CREDIT","BONUS_CREDIT","PROMOTIONAL_CREDIT","REFUND_CREDIT","ADMIN_ADJUSTMENT","EXPIRATION_DEBIT","TRANSFER_IN_FUTURE","TRANSFER_OUT_FUTURE"]);
const BALANCE_SOURCES=Object.freeze(["monthly","purchased","bonus","promotional"]);

const freezeList=list=>Object.freeze(list.map(value=>Object.freeze({...value})));
const transactionId=(wallet,key)=>`${wallet.id}:${wallet.version+1}:${key}`;
export const walletBalance=wallet=>BALANCE_SOURCES.reduce((sum,key)=>sum+Number(wallet.balances[key]||0),0);

export function createWallet({id,ownerId,type="personal",workspaceId=null,monthlyAllocation=0,purchased=0,bonus=0,promotional=0,rolloverPolicy=null,expirationPolicy={},resetDate=null,status="active"}){
  if(!WALLET_TYPES.includes(type))throw new TypeError("Unknown wallet type");
  const balances={monthly:Number(monthlyAllocation)||0,purchased:Number(purchased)||0,bonus:Number(bonus)||0,promotional:Number(promotional)||0};
  return Object.freeze({id,ownerId,type,workspaceId,balances:Object.freeze(balances),monthlyAllocation:Number(monthlyAllocation)||0,rolloverPolicy,expirationPolicy:Object.freeze({...expirationPolicy}),resetDate,status,ledger:Object.freeze([]),history:Object.freeze([]),version:1});
}

function appendLedger(wallet,{type,amount,reason,idempotencyKey,missionId=null,accountId=wallet.ownerId,workspaceId=wallet.workspaceId,subscriptionTier=null,createdBy="system",metadata={},at=new Date().toISOString()},balances){
  if(!LEDGER_TRANSACTION_TYPES.includes(type))throw new TypeError("Unknown ledger transaction type");
  if(!idempotencyKey)throw new TypeError("Idempotency key required");
  if(wallet.ledger.some(item=>item.idempotencyKey===idempotencyKey))return wallet;
  const before=walletBalance(wallet),after=BALANCE_SOURCES.reduce((sum,key)=>sum+Number(balances[key]||0),0);
  const entry=Object.freeze({transactionId:transactionId(wallet,idempotencyKey),walletId:wallet.id,missionId,accountId,workspaceId,type,amount,balanceBefore:before,balanceAfter:after,reason,subscriptionTier,createdAt:at,createdBy,idempotencyKey,metadata:Object.freeze({...metadata})});
  return Object.freeze({...wallet,balances:Object.freeze(balances),ledger:Object.freeze([...wallet.ledger,entry]),history:Object.freeze([...wallet.history,entry]),version:wallet.version+1});
}

export function allocateMonthly(wallet,{amount,periodKey,tier=null,at=new Date().toISOString()}){return appendLedger(wallet,{type:"MONTHLY_ALLOCATION",amount:Number(amount)||0,reason:"monthly_allocation",idempotencyKey:`monthly:${periodKey}`,subscriptionTier:tier,metadata:{periodKey},at},{...wallet.balances,monthly:Number(amount)||0});}
export function addCoins(wallet,{source,amount,reference,expiresAt=null,at=new Date().toISOString()}){if(!["purchased","bonus","promotional"].includes(source))throw new TypeError("Invalid coin source");if(source==="purchased"&&!PURCHASES_ENABLED)return wallet;const value=Math.max(0,Number(amount)||0),type={purchased:"PURCHASED_COIN_CREDIT",bonus:"BONUS_CREDIT",promotional:"PROMOTIONAL_CREDIT"}[source];return appendLedger(wallet,{type,amount:value,reason:`${source}_credit`,idempotencyKey:`credit:${reference}`,metadata:{source,expiresAt},at},{...wallet.balances,[source]:wallet.balances[source]+value});}
export function recordFreeMissionAction(wallet,{missionId,action,at=new Date().toISOString()}){if(!FREE_ACTIONS.includes(action))throw new TypeError("Action is not free");return Object.freeze({...wallet,history:Object.freeze([...wallet.history,Object.freeze({type:"FREE_ACTION",missionId,action,amount:0,coins:0,createdAt:at})])});}

export function createMissionLifecycle({missionId,accountId,workspaceId=null,contextComplete=false,onePickPrepared=false,domainPreparationComplete=false,approvalReady=false,state="MISSION_CREATED"}){if(!MISSION_STATES.includes(state))throw new TypeError("Unknown mission state");return Object.freeze({missionId,accountId,workspaceId,state,contextComplete,onePickPrepared,domainPreparationComplete,approvalReady,completionConfirmed:false,stateHistory:Object.freeze([state]),versionHistoryId:missionId});}
export function transitionMission(mission,nextState,{actorId=null}={}){if(!MISSION_STATES.includes(nextState))throw new TypeError("Unknown mission state");const eligible=mission.contextComplete&&mission.onePickPrepared&&mission.domainPreparationComplete&&mission.approvalReady;if(nextState==="READY_FOR_COMPLETION"&&!eligible)throw new Error("Mission is not approval-ready");if(nextState==="USER_CONFIRMED_COMPLETE"&&mission.state!=="READY_FOR_COMPLETION")throw new Error("Explicit completion requires READY_FOR_COMPLETION");if(nextState==="MISSION_COMPLETED"&&!(mission.state==="USER_CONFIRMED_COMPLETE"&&mission.completionConfirmed))throw new Error("User confirmation required");return Object.freeze({...mission,state:nextState,completionConfirmed:nextState==="USER_CONFIRMED_COMPLETE"?true:mission.completionConfirmed,confirmedBy:nextState==="USER_CONFIRMED_COMPLETE"?actorId:mission.confirmedBy,stateHistory:Object.freeze([...mission.stateHistory,nextState])});}

export function consumeCompletedMission(wallet,{missionId,status,completionReference,versionHistoryId=missionId,accountId=wallet.ownerId,workspaceId=wallet.workspaceId,subscriptionTier=null,authorized=true,at=new Date().toISOString()}){
  const normalized=status==="completed"?"MISSION_COMPLETED":status;
  if(!authorized)return{wallet,consumed:false,reason:"unauthorized_completion"};
  if(normalized!=="MISSION_COMPLETED")return{wallet,consumed:false,reason:"mission_not_completed"};
  if(!completionReference)return{wallet,consumed:false,reason:"completion_reference_required"};
  const key=`mission-completion:${versionHistoryId}`;
  if(wallet.ledger.some(item=>item.type===CHARGEABLE_EVENT&&item.idempotencyKey===key))return{wallet,consumed:false,reason:"already_consumed"};
  if(walletBalance(wallet)<1)return{wallet,consumed:false,reason:"insufficient_mission_coins",upgradeRequired:true,preparedMissionVisible:true};
  const balances={...wallet.balances};for(const source of COIN_POLICY.spendingOrder){if(balances[source]>0){balances[source]-=1;break;}}
  const next=appendLedger(wallet,{type:CHARGEABLE_EVENT,amount:-1,reason:"mission_completed",idempotencyKey:key,missionId,accountId,workspaceId,subscriptionTier,metadata:{completionReference,versionHistoryId},at},balances);
  return{wallet:next,consumed:true,reason:"mission_completed"};
}

export function createEntitlementEngine(catalog=SUBSCRIPTION_CATALOG){return Object.freeze({catalog,resolve(tier,key,context={}){if(!TIER_KEYS.includes(tier)||!ENTITLEMENT_KEYS.includes(key))return Object.freeze({state:"disabled",quantity:null,source:"default"});const base=catalog[tier].entitlements[key];const override=context.administrativeOverride??context.promotionalOverride;return Object.freeze({...base,...(override||{}),source:override?"override":"plan"});},allows(tier,key,context={}){return["enabled","limited"].includes(this.resolve(tier,key,context).state);}});}
export function createFeatureFlags(catalog=SUBSCRIPTION_CATALOG){const engine=createEntitlementEngine(catalog);return Object.freeze(Object.fromEntries(TIER_KEYS.map(tier=>[tier,Object.freeze(Object.fromEntries(ENTITLEMENT_KEYS.map(key=>[key,engine.allows(tier,key)]))) ])));}
export function hasFeature({tier,feature,flags=createFeatureFlags(),engine=null}){return engine?engine.allows(tier,feature):flags[tier]?.[feature]===true;}
export function subscriptionAccess({tier="free",catalog=SUBSCRIPTION_CATALOG,flags=createFeatureFlags(catalog)}){if(!TIER_KEYS.includes(tier))throw new TypeError("Unknown tier");return Object.freeze({tier,plan:catalog[tier],flags:flags[tier]||{}});}
export function changeTier(account,nextTier,{catalog=SUBSCRIPTION_CATALOG,effectiveAt="period_end"}={}){if(!TIER_KEYS.includes(nextTier))throw new TypeError("Unknown tier");const inactive=ENTITLEMENT_KEYS.filter(key=>account.plan?.entitlements?.[key]?.state!=="disabled"&&catalog[nextTier].entitlements[key].state==="disabled");return Object.freeze({...account,tier:nextTier,plan:catalog[nextTier],planAdjustmentRequired:Boolean(account.members?.length>Number(catalog[nextTier].memberLimit||Infinity)),history:Object.freeze([...(account.history||[]),Object.freeze({type:"tier_changed",from:account.tier,to:nextTier,effectiveAt,at:new Date().toISOString()})]),missionHistory:Object.freeze([...(account.missionHistory||[])]),receipts:Object.freeze([...(account.receipts||[])]),missionMemory:Object.freeze({...account.missionMemory}),workspaceData:Object.freeze({...account.workspaceData}),inactiveFeatures:Object.freeze(inactive)});}

const ALL=PERMISSION_KEYS;
const ROLE_PERMISSIONS=Object.freeze({owner:ALL,parent:["view_mission","create_mission","edit_own_mission","edit_shared_mission","approve_mission","complete_mission","view_wallet","invite_member","remove_member","view_shared_memory","edit_shared_memory"],adult_member:["view_mission","create_mission","edit_own_mission","view_wallet","view_shared_memory"],child_member:["view_mission","create_mission","edit_own_mission"],dependent:["view_mission"],organizer:["view_mission","create_mission","edit_own_mission","edit_shared_mission","approve_mission","complete_mission","invite_member","remove_member"],admin:["view_mission","create_mission","edit_own_mission","edit_shared_mission","approve_mission","complete_mission","invite_member","remove_member","manage_roles","view_shared_memory","edit_shared_memory","manage_workspace"],member:["view_mission","create_mission","edit_own_mission"],workspace_admin:["view_mission","create_mission","edit_own_mission","edit_shared_mission","approve_mission","complete_mission","view_wallet","manage_wallet","invite_member","remove_member","manage_roles","view_shared_memory","edit_shared_memory","view_analytics","manage_workspace","view_audit_log"],finance_admin:["view_mission","approve_mission","view_wallet","manage_wallet","view_analytics","manage_billing_future","view_audit_log"],manager:["view_mission","create_mission","edit_own_mission","edit_shared_mission","approve_mission","complete_mission","view_wallet","invite_member"],employee:["view_mission","create_mission","edit_own_mission","view_shared_memory"],travel_coordinator:["view_mission","create_mission","edit_own_mission","edit_shared_mission","approve_mission","complete_mission"],guest:["view_mission"],viewer:["view_mission"]});
export function rolePermissions(role,overrides={}){if(!ROLE_KEYS.includes(role))throw new TypeError("Unknown role");return Object.freeze([...(overrides[role]||ROLE_PERMISSIONS[role])]);}
export function createWorkspace({id,type,ownerId,wallet,members=[],departments=[],subscriptionTier="free",policies={}}){if(!["family","group","business","enterprise"].includes(type))throw new TypeError("Invalid workspace type");const normalized=[{userId:ownerId,role:"owner",status:"active"},...members.filter(member=>member.userId!==ownerId).map(member=>({userId:member.userId,role:ROLE_KEYS.includes(member.role)?member.role:"viewer",status:member.status||"active"}))];return Object.freeze({id,type,ownerId,wallet,members:freezeList(normalized),departments:freezeList(departments),subscriptionTier,policies:Object.freeze({...policies}),history:Object.freeze([])});}
export function can(workspace,userId,permission,overrides={}){if(!PERMISSION_KEYS.includes(permission))return false;const member=workspace.members.find(item=>item.userId===userId&&item.status==="active");return Boolean(member&&rolePermissions(member.role,overrides).includes(permission));}
export function canAccessWallet(workspace,userId,walletId=workspace.wallet?.id){return workspace.wallet?.id===walletId&&can(workspace,userId,"view_wallet");}
export function selectWorkspaceContext({accountId,workspace,missionPurpose="shared"}){if(!workspace)return Object.freeze({accountId,contextType:"personal",walletId:`personal:${accountId}`,visible:true});if(!workspace.members.some(member=>member.userId===accountId&&member.status==="active"))throw new Error("Cross-workspace access denied");if(missionPurpose==="personal"&&workspace.type!=="family")throw new Error("Personal mission requires personal context");return Object.freeze({accountId,contextType:workspace.type,workspaceId:workspace.id,walletId:workspace.wallet.id,visible:true,subscriptionTier:workspace.subscriptionTier});}

export function createSharedMemory({workspaceId,entries=[]}){return Object.freeze({workspaceId,entries:freezeList(entries.map(entry=>({...entry,shared:entry.shared===true,contributors:Object.freeze([...(entry.contributors||[])]),pausedBy:Object.freeze([...(entry.pausedBy||[])])})))});}
export function shareMemory(memory,{actorId,key,value,category,consent=false}){if(!consent)throw new Error("Shared memory consent required");if(/password|payment|passport|government.?id|medical|health record|legal document/i.test(`${key} ${category}`))throw new Error("Sensitive memory is not allowed");return Object.freeze({...memory,entries:Object.freeze([...memory.entries,Object.freeze({id:`${memory.workspaceId}:${key}`,key,value,category,shared:true,addedBy:actorId,contributors:Object.freeze([actorId]),pausedBy:Object.freeze([])})])});}
export function visibleSharedMemory(memory,{userId,workspace}){if(!workspace.members.some(member=>member.userId===userId&&member.status==="active")||!can(workspace,userId,"view_shared_memory"))return Object.freeze([]);return Object.freeze(memory.entries.filter(entry=>entry.shared&&!entry.pausedBy.includes(userId)));}

export function coordinateFamily({members,events,transport={}}){return Object.freeze({members:freezeList(members),sharedCalendar:freezeList(events),meetingPointStatus:transport.meetingPoint?"prepared":"needs_location",arrivalSynchronization:members.every(item=>item.arrivalTime)?"prepared":"needs_arrival_times",safeReturnHome:members.every(item=>item.returnPlan)?"prepared":"needs_return_plans",reservations:Object.freeze([]),coinRule:"one_mission_one_coin",executionEnabled:false});}
export function coordinateGroup({attendees=[],itinerary=[],roles={}}){return Object.freeze({attendance:freezeList(attendees),sharedItinerary:freezeList(itinerary),roles:Object.freeze({...roles}),transportationStatus:"preparation_only",reservations:Object.freeze([]),coinRule:"one_mission_one_coin",executionEnabled:false});}
export function createBusinessWorkspace(input){return createWorkspace({...input,type:input.type||"business"});}
export function createEnterpriseHierarchy({workspaceId,ownerId,wallet,departments=[],members=[]}){const workspace=createWorkspace({id:workspaceId,type:"enterprise",ownerId,wallet,departments,members,subscriptionTier:"one_enterprise"});return Object.freeze({...workspace,ssoReady:true,scimReady:true,apiReady:true,auditLog:Object.freeze([]),approvalChains:Object.freeze([]),integrations:Object.freeze([]),regionalPolicies:Object.freeze([])});}
export function missionValueScore({participants=1,providers=1,locations=1,itinerarySteps=1,liveSources=0,transportModes=1,revisions=0,approvalSteps=1,riskLevel=0}){const factors={participants,providers,locations,itinerarySteps,liveSources,transportModes,revisions,approvalSteps,riskLevel};const score=Math.min(100,Object.values(factors).reduce((sum,value)=>sum+Math.max(0,Number(value)||0),0)*3),band=score<25?"LOW":score<55?"MEDIUM":score<80?"HIGH":"COMPLEX";return Object.freeze({valueScore:score,complexityBand:band,reasonFactors:Object.freeze(factors),billingImpact:false});}

export function upgradeState(wallet,language="en"){if(walletBalance(wallet)>0)return{required:false,canReview:true,preparedMissionVisible:true,message:null};return{required:true,canReview:true,preparedMissionVisible:true,message:language==="ko"?"미션이 준비되었습니다. 이번 달 미션 코인을 모두 사용했습니다. 플랜을 업그레이드하거나 미션 코인을 추가해 완료하세요.":"Your mission is ready. You have used this month's Mission Coins. Upgrade your plan or add Mission Coins to complete it."};}
export function createBillingAdapter(name){const blocked=operation=>({status:"blocked",reason:"billing_execution_disabled",operation});return Object.freeze({name,enabled:BILLING_EXECUTION_ENABLED,externalCalls:false,async createCustomer(){return blocked("create_customer")},async createSubscription(){return blocked("create_subscription")},async upgradeSubscription(){return blocked("upgrade_subscription")},async downgradeSubscription(){return blocked("downgrade_subscription")},async cancelSubscription(){return blocked("cancel_subscription")},async pauseSubscription(){return blocked("pause_subscription")},async resumeSubscription(){return blocked("resume_subscription")},async purchaseMissionCoins(){return blocked("purchase_mission_coins")},async issueRefund(){return blocked("issue_refund")},async retrieveInvoices(){return blocked("retrieve_invoices")},async handleWebhookEvent(){return blocked("handle_webhook_event")},async quote(){return{status:"unavailable",reason:"billing_not_connected"}},async checkout(){return blocked("checkout")},async subscribe(){return blocked("subscribe")}});}
export const BILLING_ADAPTERS=Object.freeze(["Stripe","Apple App Store","Google Play","KakaoPay","Naver Pay","PayPal","Regional"].map(createBillingAdapter));
export function createSupportCase({caseId,accountId,workspaceId=null,missionId=null,priority="STANDARD",assignedTeam=null,status="NEW",escalationLevel=0}){return Object.freeze({caseId,accountId,workspaceId,missionId,priority,assignedTeam,assignedHumanFuture:null,status,escalationLevel,capability:"Future capability",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}
export function missionEconomyAnalytics(events=[]){const safe=events.map(({type,category="unknown",planningMinutes,satisfaction,workspaceType,approvalDuration,reopened=false})=>({type,category,planningMinutes,satisfaction,workspaceType,approvalDuration,reopened})),completed=safe.filter(item=>item.type===CHARGEABLE_EVENT),durations=completed.map(item=>Number(item.planningMinutes)).filter(Number.isFinite),satisfaction=completed.map(item=>Number(item.satisfaction)).filter(Number.isFinite);return Object.freeze({completedMissions:completed.length,missionCategories:Object.freeze(completed.reduce((all,item)=>(all[item.category]=(all[item.category]||0)+1,all),{})),averagePlanningTime:durations.length?durations.reduce((a,b)=>a+b,0)/durations.length:null,missionCoinUsage:completed.length,unusedMonthlyAllocation:null,upgradeTriggerPoint:safe.findIndex(item=>item.type==="UPGRADE_SHOWN"),missionSuccessRate:safe.length?completed.length/safe.length:null,missionSatisfaction:satisfaction.length?satisfaction.reduce((a,b)=>a+b,0)/satisfaction.length:null,familyCoordinationFrequency:safe.filter(item=>item.workspaceType==="family").length,groupCoordinationFrequency:safe.filter(item=>item.workspaceType==="group").length,businessCoordinationFrequency:safe.filter(item=>["business","enterprise"].includes(item.workspaceType)).length,missionReopenRate:safe.length?safe.filter(item=>item.reopened).length/safe.length:null});}
export function configuredCatalog(overrides={}){return configureSubscriptionCatalog(overrides);}
export const SAFETY_STATE=Object.freeze({billingExecutionEnabled:BILLING_EXECUTION_ENABLED,purchasesEnabled:PURCHASES_ENABLED,transfersEnabled:TRANSFERS_ENABLED,providerContactEnabled:false,externalExecutionEnabled:false});
