import { trackEvent } from "./js/analytics.js";
const language=localStorage.getItem("kastiz-one-language")||(navigator.language.startsWith("ko")?"ko":"en");
const theme=localStorage.getItem("kastiz-one-theme")||"light";document.documentElement.lang=language;document.documentElement.dataset.theme=theme;
const copy={en:{pricing:"Pricing",settings:"Settings",status:"SECURE ACCOUNT ACCESS",title:"Sign in to Kastiz ONE",copy:"Your missions and chosen preferences can be protected by your account.",email:"Email",password:"Password",displayName:"Display name",signIn:"Sign in",createAccount:"Create account",resetPassword:"Reset password",waitlist:"Join waitlist",request:"Request early access",support:"Contact support",forgot:"Forgot password",privacy:"Privacy request",deletion:"Account deletion & data export",preferences:"Mission history, notifications, language & theme settings",emailOpen:"Enter your email and password.",oauthPending:"{provider} sign-in requires secure provider configuration.",offline:"Secure accounts are not configured on this preview yet. No password was stored.",sent:"If the account exists, reset instructions were sent.",registered:"Check your email to verify the account before signing in."},ko:{pricing:"요금제",settings:"설정",status:"안전한 계정 로그인",title:"Kastiz ONE 로그인",copy:"미션과 선택한 설정을 계정으로 안전하게 보호할 수 있습니다.",email:"이메일",password:"비밀번호",displayName:"표시 이름",signIn:"로그인",createAccount:"계정 만들기",resetPassword:"비밀번호 재설정",waitlist:"대기 명단 참여",request:"얼리 액세스 요청",support:"지원 문의",forgot:"비밀번호 찾기",privacy:"개인정보 요청",deletion:"계정 삭제 및 데이터 내보내기",preferences:"미션 기록, 알림, 언어 및 테마 설정",emailOpen:"이메일과 비밀번호를 입력하세요.",oauthPending:"{provider} 로그인은 안전한 제공업체 설정이 필요합니다.",offline:"이 미리보기에는 아직 안전한 계정이 설정되지 않았습니다. 비밀번호는 저장되지 않았습니다.",sent:"계정이 존재하면 재설정 안내를 전송했습니다.",registered:"로그인 전에 이메일에서 계정을 확인하세요."}}[language];
document.querySelectorAll("[data-i18n]").forEach(el=>{if(copy[el.dataset.i18n])el.textContent=copy[el.dataset.i18n]});document.querySelectorAll(".logo img,.one-logo img").forEach(img=>img.classList.toggle("light-logo",theme==="light"));
const status=document.getElementById("providerStatus"),form=document.getElementById("emailAuthForm"),displayRow=document.getElementById("displayNameRow");
async function api(path,options={}){const response=await fetch(`/api/v1/${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error?.message||copy.offline);return data;}
document.querySelectorAll("[data-provider]").forEach(button=>button.addEventListener("click",()=>{const provider=button.dataset.provider;if(provider==="Email"){form.hidden=false;status.textContent=copy.emailOpen;document.getElementById("authEmail").focus();}else status.textContent=copy.oauthPending.replace("{provider}",provider);trackEvent("login_provider_selected",{page:"login",language,provider:provider.toLowerCase(),status:provider==="Email"?"form_opened":"configuration_required"});}));
document.querySelector('[data-auth-action="register"]').addEventListener("click",async()=>{if(form.dataset.mode!=="register"){displayRow.hidden=false;document.getElementById("authDisplayName").required=true;form.dataset.mode="register";status.textContent=language==="ko"?"이름, 이메일, 비밀번호를 입력한 뒤 계정 만들기를 다시 누르세요.":"Enter name, email and password, then choose Create account again.";return;}const payload={email:document.getElementById("authEmail").value,password:document.getElementById("authPassword").value,displayName:document.getElementById("authDisplayName").value,language};try{await api("auth/register",{method:"POST",body:JSON.stringify(payload)});status.textContent=copy.registered;}catch(e){status.textContent=e.message;}});
document.querySelector('[data-auth-action="reset"]').addEventListener("click",async()=>{const email=document.getElementById("authEmail").value;if(!email)return document.getElementById("authEmail").focus();try{await api("auth/password-reset",{method:"POST",body:JSON.stringify({email})});status.textContent=copy.sent;}catch(e){status.textContent=e.message;}});
form.addEventListener("submit",async event=>{event.preventDefault();const buttons=[...form.querySelectorAll("button")];buttons.forEach(b=>b.disabled=true);try{await api("auth/login",{method:"POST",body:JSON.stringify({email:document.getElementById("authEmail").value,password:document.getElementById("authPassword").value})});location.href=new URL("profile.html",location.href).href;}catch(e){status.textContent=e.message;}finally{buttons.forEach(b=>b.disabled=false);}});
trackEvent("page_visit",{page:"login",language});
