import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const followup = readFileSync(new URL("../js/ui/mission-followup.js", import.meta.url), "utf8");
const loading = readFileSync(new URL("../js/pages/loading-page.js", import.meta.url), "utf8");
const results = readFileSync(new URL("../js/pages/results-page.js", import.meta.url), "utf8");
const resultsHtml = readFileSync(new URL("../results.html", import.meta.url), "utf8");
const resultsCss = readFileSync(new URL("../results.css", import.meta.url), "utf8");
const loadingHtml = readFileSync(new URL("../loading.html", import.meta.url), "utf8");
const indexHtml = readFileSync(new URL("../index.html", import.meta.url), "utf8");
const homeCss = readFileSync(new URL("../style.css", import.meta.url), "utf8");
const login = readFileSync(new URL("../login.js", import.meta.url), "utf8");
const loginHtml = readFileSync(new URL("../login.html", import.meta.url), "utf8");
const profileHtml = readFileSync(new URL("../profile.html", import.meta.url), "utf8");
const profilePage = readFileSync(new URL("../js/pages/profile-page.js", import.meta.url), "utf8");

assert.match(followup, /GT:\s*"GTQ"|Guatemala:\s*"GT"/);
assert.match(followup, /"Central America":\s*"BZ CR SV GT HN NI PA"/);
for (const code of ["PH", "CG", "CD", "ZA", "KH", "MY", "TW", "PG"]) {
  assert.match(followup, new RegExp(`\\b${code}\\b`), `${code} must exist in the offline worldwide country catalog`);
}
assert.match(followup, /buildStaticWorldwideCountries/);
assert.match(followup, /Promise\.allSettled/);
assert.match(followup, /searchWorldwideDestinations/);
assert.match(followup, /export const detectWorldwideTravelDestination/);
assert.match(followup, /item\.city, item\.country, item\.countryKo/);
assert.match(followup, /dedupe=0&limit=25/);
assert.match(followup, /data-destination-matches/);
assert.match(followup, /destinationCandidateLabel/);
assert.match(followup, /KNOWN_AMBIGUOUS_DESTINATIONS/);
assert.match(followup, /country: "India"[\s\S]*city: "Surat"/);
assert.match(followup, /country: "France"[\s\S]*city: "Surat"/);
assert.doesNotMatch(followup, /renderDestinationMatches\(matches\);\s*showResolvedDestination\(matches\[0\]\);/);
assert.match(followup, /Matching locations \(optional\)/);
assert.ok(followup.indexOf('data-destination-matches hidden') < followup.indexOf('data-destination-level="continent"'), "matching locations must appear before the full destination hierarchy");
assert.match(followup, /destinationInput\.dispatchEvent\(new Event\("input"/);
assert.match(followup, /has-destination-matches/);
assert.match(followup, /suffixPhrase/);
assert.match(followup, /koreanPhrase/);
assert.match(followup, /resolvedDestination = matches\[0\]/);
assert.doesNotMatch(followup, /Several places share this name\. Choose the exact place and country\./);
assert.match(followup, /showResolvedDestination\(matches\[0\]\)/);
assert.match(followup, /stateSelect\.value = resolved\.state/);
assert.match(followup, /fillCities\(resolved\.country, resolved\.city \|\| "", resolved\.state \|\| "", true\)/);
assert.doesNotMatch(followup, /restcountries\.com\/v3/);
assert.match(loading, /countriesnow\.space\/api\/v0\.1\/countries\/capital/);
assert.match(loading, /open\.er-api\.com\/v6\/latest/);
assert.match(loading, /geocoding-api\.open-meteo\.com/);
assert.match(loading, /overpass-api\.de\/api\/interpreter/);
assert.match(loading, /nwr\(around:3500/);
assert.match(loading, /nwr\(around:6000/);
assert.match(loading, /bounded=1&viewbox=/);
assert.match(loading, /tourism~"hotel\|hostel\|guest_house\|motel\|apartment"/);
assert.match(loading, /amenity~"restaurant\|cafe\|fast_food"/);
assert.match(loading, /out center 30/);
assert.match(loading, /out center 20/);
assert.match(loading, /for \(const \[index, query\] of placeQueries\.entries\(\)\)/);
assert.match(loading, /overpass\.kumi\.systems/);
assert.match(loading, /q=restaurant/);
assert.match(loading, /OpenStreetMap Nominatim/);
assert.match(loading, /q=hotel/);
assert.match(loading, /www\.gov\.uk\/api\/content\/foreign-travel-advice/);
assert.match(loading, /youtube\.com\/results\?search_query/);
assert.match(loading, /overseas\.mofa\.go\.kr/);
assert.match(loading, /learnenglish\.britishcouncil\.org/);
assert.match(loading, /map\.naver\.com\/p\/search/);
assert.match(loading, /식당 네이버 예약/);
assert.match(results, /createPublicResourceCard/);
assert.match(followup, /How much can you spend\? \(optional\)/);
assert.match(followup, /총 예산은 얼마인가요\?/);
assert.match(followup, /아직 모르겠다면 비워두세요\. ONE이 다양한 가격대를 비교해드려요\./);
assert.match(followup, /Best overall balance/);
assert.match(followup, /가격·품질·시간을 고르게/);
assert.match(followup, /!\["budget", "housingBudget", "preferences"/);
assert.doesNotMatch(results, /budgetFriendlyTier/);
assert.doesNotMatch(results, /recommendedTier/);
assert.doesNotMatch(results, /luxuryTier/);
assert.match(results, /PROTOTYPE_MISSION_ARCHIVE_KEY/);
assert.match(results, /savePrototypeMission\(reference\)/);
assert.match(results, /requestedReference/);
const home = readFileSync(new URL("../js/pages/home-page.js", import.meta.url), "utf8");
assert.match(home, /await detectWorldwideTravelDestination\(mission, activeLanguage\)/);
assert.match(home, /pendingFollowUp\?\.type \|\| classifyMission/);
assert.match(home, /reopenPrototypeMission/);
assert.match(home, /detectPrototypeReferenceInImage/);
assert.match(home, /TextDetector/);
assert.match(home, /BarcodeDetector/);
assert.match(results, /api\.qrserver\.com\/v1\/create-qr-code/);
assert.match(results, /prototype-reference-qr/);
assert.match(results, /getPortableSharedResult/);
assert.match(results, /p: 1, r: reference/);
assert.match(results, /parsed\?\.p !== 1/);
assert.match(results, /Scan with your phone camera to reopen this summary/);
assert.match(home, /url\.searchParams\.has\("share"\)/);
assert.match(results, /GT:\s*\[\["Aeromexico"/);
assert.match(results, /GT:\s*\[\[2300000, 3900000\]/);
assert.match(results, /liveHotelNames/);
assert.match(results, /liveHotelNames, \.\.\.\(profile\.hotels \|\| \[\]\), \.\.\.hotelFallbacks/);
assert.match(results, /liveRestaurantPlaces/);
assert.match(results, /providerSource: source \|\| "Prototype curated fallback"/);
assert.match(indexHtml, /script\.js\?v=20260720-no-outcome-popup/);
assert.match(indexHtml, /style\.css\?v=20260717-30/);
assert.match(homeCss, /mission-followup-date-field \{ width: min\(100%, 230px\)/);
assert.match(homeCss, /max-height: calc\(100dvh - 24px\); margin: auto; border-radius: 24px/);
assert.match(loadingHtml, /loading\.js\?v=20260719-language-v1/);
assert.match(resultsHtml, /results\.js\?v=20260722-experience-expansion/);
assert.match(resultsHtml, /results\.css\?v=20260717-46/);
assert.match(resultsCss, /information-review-content li span\{[^}]*white-space:nowrap/);
assert.match(resultsCss, /@media\(max-width:520px\)[\s\S]*information-review-content li\{display:flex/);
assert.match(results, /currentResult\?\.portableShare === true \|\|/);
assert.match(results, /document\.body\.classList\.add\("portable-summary-view"\)/);
assert.match(results, /approvalPanel\.hidden = false/);
assert.match(results, /approvalList\.hidden = true/);
assert.match(resultsCss, /\.portable-summary-view \.mission-hero/);
assert.match(resultsCss, /prototype-reference-qr \{[^}]*width: min\(320px, 86vw\)/);
assert.match(results, /const portableChecklist = parsed\.l === "ko"/);
assert.match(results, /\?share=\$\{encodeURIComponent\(encodePortableShare\(portableResult\)\)\}/);
assert.doesNotMatch(results, /\?reference=\$\{encodeURIComponent\(reference\)\}&share=/);
assert.match(results, /size=900x900&amp;format=png&amp;ecc=L&amp;qzone=8/);
assert.match(results, /d: \[portableCountry, "", portableCity, ""\]/);
assert.match(results, /f: flight \? \[portableFlightName, ""/);
assert.match(results, /w: weatherItems, e: currencyItems/);
assert.match(results, /weekday: "short"/);
assert.match(resultsCss, /data-card-id="flights"[^}]*\.option-value[^}]*flex-wrap: nowrap/);
assert.match(resultsCss, /completion-message > p[^}]*white-space: normal/);
assert.match(home, /SE: "SEK"/);
assert.doesNotMatch(loading, /exchangeRate\?\.to \|\| "JPY"/);
assert.match(results, /preparedByOne: "ONE 이 준비했습니다\."/);
assert.match(results, /flightEstimateNotice: "Estimated price range · not a live fare"/);
assert.match(results, /google\.com\/travel\/flights\?q=/);
assert.match(results, /priceBasis: "prototype_market_estimate"/);
assert.doesNotMatch(results, /priceCheckedAt:/);
assert.match(results, /const selected = option === recommendation \|\| option === chosen/);
assert.match(resultsCss, /mission-timeline \{ justify-content: center; flex-wrap: wrap/);
assert.match(resultsCss, /execution-summary-item \{[^}]*text-align: center/);
assert.match(results, /<a class="all-in-slogan" href="index\.html"/);
assert.match(results, /returnHomeNow: "HOME"/);
assert.match(results, /\^KLM\(\?:\\s\|\$\)/);
assert.doesNotMatch(results, /accommodation — live provider confirmation required/);
assert.doesNotMatch(results, /central hotel — provider confirmation required/);
assert.match(results, /goalAliases = \{ la: cityName \|\| "Los Angeles"/);
assert.match(resultsCss, /data-card-id="exchange-rate"[^}]*grid-template-rows: none; grid-auto-flow: row/);
assert.match(resultsCss, /mission-understood-goal strong \{ font-size: clamp\(24px/);
assert.match(results, /\.slice\(0, 6\);\n  const liveRestaurantPlaces/);
assert.match(results, /profile\.hotels = hotelPool\.slice\(0, hotelPool\.length >= 6 \? 6 : 4\)/);
assert.match(results, /class="restaurant-entry"/);
assert.match(resultsCss, /\.mission-understood \{[\s\S]*?text-align: center;/);
assert.match(resultsCss, /\.mission-understood-items \{[^}]*justify-content: center/);
assert.match(resultsCss, /\.completion-message h3 \{[\s\S]*?font-size: clamp\(34px, 6vw, 56px\)/);
assert.match(resultsCss, /\.execution-summary-head h4 \{[^}]*font-size: clamp\(21px, 3\.2vw, 32px\)/);
assert.match(resultsCss, /selectable-recommendation \.recommendation-value \{ flex-direction: column; align-items: center; flex-wrap: nowrap/);
assert.match(results, /const properCaseLocation/);
assert.match(results, /value: approvalMissionName\(\)/);
assert.match(login, /new URL\("profile\.html",location\.href\)/);
assert.doesNotMatch(loginHtml, /class="provider"[^>]*disabled/);
assert.match(profileHtml, /id="starterProfileForm"/);
assert.match(profileHtml, /Do not enter a full address, payment information, passport/);
assert.match(profilePage, /setMemoryEnabled\(true\)/);
assert.match(profilePage, /updatePreference\(category,key,value,"profile-onboarding"\)/);

console.log("destination reliability checks passed");
