import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const followup = readFileSync(new URL("../js/ui/mission-followup.js", import.meta.url), "utf8");
const loading = readFileSync(new URL("../js/pages/loading-page.js", import.meta.url), "utf8");
const results = readFileSync(new URL("../js/pages/results-page.js", import.meta.url), "utf8");
const resultsHtml = readFileSync(new URL("../results.html", import.meta.url), "utf8");
const loadingHtml = readFileSync(new URL("../loading.html", import.meta.url), "utf8");
const indexHtml = readFileSync(new URL("../index.html", import.meta.url), "utf8");

assert.match(followup, /GT:\s*"GTQ"|Guatemala:\s*"GT"/);
assert.match(followup, /"Central America":\s*"BZ CR SV GT HN NI PA"/);
for (const code of ["PH", "CG", "CD", "ZA", "KH", "MY", "TW", "PG"]) {
  assert.match(followup, new RegExp(`\\b${code}\\b`), `${code} must exist in the offline worldwide country catalog`);
}
assert.match(followup, /buildStaticWorldwideCountries/);
assert.match(followup, /Promise\.allSettled/);
assert.match(followup, /searchWorldwideDestinations/);
assert.match(followup, /export const detectWorldwideTravelDestination/);
assert.match(followup, /item\.city, item\.country, item\.countryKo/);
assert.match(followup, /dedupe=0&limit=25/);
assert.match(followup, /data-destination-matches/);
assert.match(followup, /destinationCandidateLabel/);
assert.match(followup, /KNOWN_AMBIGUOUS_DESTINATIONS/);
assert.match(followup, /country: "India"[\s\S]*city: "Surat"/);
assert.match(followup, /country: "France"[\s\S]*city: "Surat"/);
assert.doesNotMatch(followup, /renderDestinationMatches\(matches\);\s*showResolvedDestination\(matches\[0\]\);/);
assert.match(followup, /Matching locations \(optional\)/);
assert.ok(followup.indexOf('data-destination-matches hidden') < followup.indexOf('data-destination-level="continent"'), "matching locations must appear before the full destination hierarchy");
assert.match(followup, /destinationInput\.dispatchEvent\(new Event\("input"/);
assert.match(followup, /has-destination-matches/);
assert.match(followup, /suffixPhrase/);
assert.match(followup, /koreanPhrase/);
assert.match(followup, /resolvedDestination = matches\[0\]/);
assert.doesNotMatch(followup, /Several places share this name\. Choose the exact place and country\./);
assert.match(followup, /showResolvedDestination\(matches\[0\]\)/);
assert.match(followup, /stateSelect\.value = resolved\.state/);
assert.match(followup, /fillCities\(resolved\.country, resolved\.city \|\| "", resolved\.state \|\| "", true\)/);
assert.doesNotMatch(followup, /restcountries\.com\/v3/);
assert.match(loading, /countriesnow\.space\/api\/v0\.1\/countries\/capital/);
assert.match(loading, /open\.er-api\.com\/v6\/latest/);
assert.match(loading, /geocoding-api\.open-meteo\.com/);
assert.match(loading, /overpass-api\.de\/api\/interpreter/);
assert.match(loading, /nwr\(around:8000/);
assert.doesNotMatch(loading, /bounded=1&viewbox=/);
assert.match(loading, /tourism~"hotel\|hostel\|guest_house\|motel\|apartment"/);
assert.match(loading, /amenity~"restaurant\|cafe\|fast_food"/);
assert.match(loading, /out center 30/);
assert.match(loading, /out center 20/);
assert.match(loading, /for \(const \[index, query\] of placeQueries\.entries\(\)\)/);
assert.match(loading, /overpass\.kumi\.systems/);
assert.match(loading, /restaurants", city, country/);
assert.match(loading, /OpenStreetMap Nominatim/);
assert.match(loading, /hotels and accommodations/);
assert.match(loading, /www\.gov\.uk\/api\/content\/foreign-travel-advice/);
assert.match(loading, /youtube\.com\/results\?search_query/);
assert.match(loading, /overseas\.mofa\.go\.kr/);
assert.match(loading, /learnenglish\.britishcouncil\.org/);
assert.match(loading, /map\.naver\.com\/p\/search/);
assert.match(loading, /식당 네이버 예약/);
assert.match(results, /createPublicResourceCard/);
assert.match(followup, /How much can you spend\? \(optional\)/);
assert.match(followup, /총 예산은 얼마인가요\?/);
assert.match(followup, /아직 모르겠다면 비워두세요\. ONE이 다양한 가격대를 비교해드려요\./);
assert.match(followup, /Best overall balance/);
assert.match(followup, /가격·품질·시간을 고르게/);
assert.match(followup, /!\["budget", "housingBudget", "preferences"/);
assert.doesNotMatch(results, /budgetFriendlyTier/);
assert.doesNotMatch(results, /recommendedTier/);
assert.doesNotMatch(results, /luxuryTier/);
assert.match(results, /PROTOTYPE_MISSION_ARCHIVE_KEY/);
assert.match(results, /savePrototypeMission\(reference\)/);
assert.match(results, /requestedReference/);
const home = readFileSync(new URL("../js/pages/home-page.js", import.meta.url), "utf8");
assert.match(home, /await detectWorldwideTravelDestination\(mission, activeLanguage\)/);
assert.match(home, /pendingFollowUp\?\.type \|\| classifyMission/);
assert.match(home, /reopenPrototypeMission/);
assert.match(home, /detectPrototypeReferenceInImage/);
assert.match(home, /TextDetector/);
assert.match(home, /BarcodeDetector/);
assert.match(results, /api\.qrserver\.com\/v1\/create-qr-code/);
assert.match(results, /prototype-reference-qr/);
assert.match(results, /GT:\s*\[\["Aeromexico"/);
assert.match(results, /GT:\s*\[\[2300000, 3900000\]/);
assert.match(results, /liveHotelNames/);
assert.match(results, /liveHotelNames, \.\.\.\(profile\.hotels \|\| \[\]\), \.\.\.hotelFallbacks/);
assert.match(results, /liveRestaurantPlaces/);
assert.match(results, /providerSource: source \|\| "Prototype curated fallback"/);
assert.match(indexHtml, /script\.js\?v=20260717-8/);
assert.match(loadingHtml, /loading\.js\?v=20260717-11/);
assert.match(resultsHtml, /results\.js\?v=20260717-7/);

console.log("destination reliability checks passed");
