import test from "node:test";
import assert from "node:assert/strict";
import { adaptExperience, buildExperienceContext, buildExperiencePack, buildExperienceReceipt, buildSamplePacks, safeExperienceMemory } from "../js/engine/experience-engine-v3.js";

test("every sample has exactly one primary ONE Pick and two selectable alternatives",()=>{for(const pack of buildSamplePacks()){assert.equal(pack.onePick.label,"⭐ ONE Pick");assert.equal(pack.alternatives.length,2);assert.equal(new Set([pack.onePick.id,...pack.alternatives.map(x=>x.id)]).size,3);}});
test("all twelve required sample missions are complete",()=>{const packs=buildSamplePacks();assert.equal(packs.length,12);for(const p of packs){assert.ok(p.missionBrief.length);assert.ok(p.onePick.itinerary.length);assert.ok(p.onePick.transport.evidence);assert.ok(p.onePick.tradeoff);assert.ok(p.oneReady.score);assert.equal(p.approval.state,"not-approved");}});
test("group context genuinely changes the recommendation",()=>{const couple=buildExperiencePack({mission:"date",group:"couple",purpose:"korea-weekend"});const family=buildExperiencePack({mission:"family",group:"family-young",purpose:"korea-weekend"});assert.notEqual(couple.onePick.title,family.onePick.title);assert.notDeepEqual(couple.onePick.itinerary,family.onePick.itinerary);});
test("decision mode changes ONE Pick",()=>{const normal=buildExperiencePack({mission:"Seoul date",group:"couple",purpose:"korea-weekend",mode:"overall"});const cheap=buildExperiencePack({mission:"Seoul date",group:"couple",purpose:"korea-weekend",mode:"money"});assert.notEqual(normal.onePick.id,cheap.onePick.id);assert.equal(cheap.onePick.identity,"Save Money");});
test("mission brief is compact",()=>{const p=buildExperiencePack({mission:"Seoul date",group:"couple",purpose:"korea-weekend"});assert.ok(p.missionBrief.length<=6);assert.doesNotMatch(p.missionBrief.join(" "),/algorithm|AI-generated|machine learning/i);});
test("trade-offs and evidence display",()=>{const p=buildExperiencePack({mission:"Seoul date",group:"couple",purpose:"korea-weekend"});assert.ok(p.onePick.tradeoff);assert.ok(p.onePick.transport.evidence);});
test("ONE Value contains no number without a valid baseline",()=>{const p=buildExperiencePack({mission:"Seoul date",purpose:"korea-weekend"});assert.equal(p.onePick.value.baselineValid,false);assert.equal("moneySaved" in p.onePick.value,false);assert.ok(p.onePick.value.convenience.length);});
test("demo data is labeled and unknown rating is not fabricated",()=>{const p=buildExperiencePack({mission:"event",purpose:"event"});assert.equal(p.onePick.providerData.sourceType,"demo");assert.match(p.dataLabels.demo,/Demo/i);assert.equal(p.onePick.rating,null);assert.equal(p.onePick.providerData.ratingStatus,"unknown");});
test("healthcare is logistical and includes disclaimer",()=>{const p=buildExperiencePack({mission:"Find a hospital for knee pain",purpose:"healthcare",group:"patient"});assert.match(p.healthcareDisclaimer,/not medical advice|not a medical judgment/i);assert.doesNotMatch(p.onePick.title,/best doctor/i);});
test("urgent healthcare language interrupts with emergency guidance",()=>{const p=buildExperiencePack({mission:"I have chest pain and cannot breathe",purpose:"healthcare"});assert.match(p.emergency,/emergency services|immediate professional/i);});
test("medical data and memory require consent",()=>{assert.deepEqual(safeExperienceMemory({selectedOption:"A"},false),{});assert.deepEqual(safeExperienceMemory({selectedOption:"A",medical:"knee pain",symptoms:"pain"},true),{selectedOption:"A"});});
test("weather backup is available for local plans",()=>{assert.ok(buildExperiencePack({mission:"Rainy Seoul",purpose:"korea-weekend",weather:"rain"}).onePick.weatherBackup);});
test("receipt neutrally records recommended and alternative selections",()=>{const p=buildExperiencePack({mission:"Seoul date",group:"couple",purpose:"korea-weekend"});const r=buildExperienceReceipt(p,p.alternatives[0].id);assert.equal(r.onePick,p.onePick.title);assert.equal(r.selected,p.alternatives[0].title);assert.equal(r.alternativeSelected,true);assert.deepEqual(r.informationShared,[]);});
test("adaptation never changes the plan automatically",()=>{const a=adaptExperience(buildExperiencePack({mission:"date"}),"late");assert.equal(a.requiresApproval,true);assert.deepEqual(a.actions,["Update Plan","Keep Original"]);});
test("English and Korean use consistent ONE branding",()=>{const en=buildExperiencePack({mission:"date",language:"en"});const ko=buildExperiencePack({mission:"데이트",language:"ko"});assert.equal(en.onePick.label,"⭐ ONE Pick");assert.equal(ko.onePick.label,"⭐ ONE Pick");assert.equal(ko.oneReady.label,"ONE Ready");assert.match(ko.missionBrief.join(""),/[가-힣]/);});

