import test from"node:test";import assert from"node:assert/strict";import{buildMissionReceiptV2,createOnePick,explainTradeoff,ONE_PICK_LABEL,oneReady,providerTrust,sanitizeMissionMemory,verifiedPickReasons}from"../js/engine/experience-engine-v2.js";
const base={cost:80,rating:80,reliability:80,refundability:80,location:80,preference:80};
test("exactly one ONE Pick is produced and alternatives remain selectable",()=>{const out=createOnePick([{...base,id:"a",name:"A",verifiedFacts:{bestValue:true}},{...base,id:"b",name:"B",cost:70}],"balanced");assert.equal(out.pick.label,ONE_PICK_LABEL);assert.equal(out.alternatives.length,1);});
test("ONE Pick reasons include only verified facts and max three",()=>{const r=verifiedPickReasons({verifiedFacts:{lowestTotalPrice:true,freeCancellation:true,directFlight:true,breakfastIncluded:true,marketingClaim:true}});assert.equal(r.length,3);assert.ok(!r.includes("marketingClaim"));});
test("tradeoffs are factual and compare cost with time",()=>{assert.match(explainTradeoff({totalCost:130000,travelMinutes:60},{totalCost:100000,travelMinutes:480}),/30,000.*420/);});
test("ONE Ready is the public readiness label",()=>{assert.equal(oneReady({requiredQuestions:true}).label,"ONE Ready");});
test("unknown provider trust remains Unknown",()=>{const trust=providerTrust({verifiedTrust:{reliability:92}});assert.equal(trust.reliability,92);assert.equal(trust.priceAccuracy,"Unknown");});
test("mission memory excludes sensitive fields",()=>{const safe=sanitizeMissionMemory({selectedOption:"Korean Air",favoriteLocations:"Tokyo Station",passport:"M123",payment:"4111",email:"a@b.com"});assert.deepEqual(safe,{selectedOption:"Korean Air",favoriteLocations:"Tokyo Station"});});
test("receipt neutrally records a different user selection",()=>{const r=buildMissionReceiptV2({receipt:{executionStatus:"Simulated only",confidenceScore:88},onePick:{name:"A"},selectedOption:{name:"B"}});assert.equal(r.selectionNote,"User selected another option.");assert.equal(r.oneReadyScore,88);});
