import test from"node:test";import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import{DevelopmentIdentityVault,ProductionIdentityVault,revealMaskedIdentity,selectIdentityFields}from"../functions/api/v1/_lib/identity-vault.js";import{assertChallenge,assertWebAuthnContext,hasWebAuthnVerifier,hasSimpleWebAuthnServer,validateRpAndOrigins,createRegistrationOptions,createAuthenticationOptions,SimpleWebAuthnServerVerifier,WebAuthnVerifier}from"../functions/api/v1/_lib/passkeys.js";import{onePassConfig}from"../functions/api/v1/_lib/one-pass-config.js";import{MockProviderAdapter}from"../functions/api/v1/_lib/one-pass-providers.js";import{TransactionCoordinator}from"../functions/api/v1/_lib/transaction-coordinator.js";
import{createApprovalPackage,assertApprovalPackage,releaseIdentityJustInTime,assertRecentSensitiveConfirmation}from"../functions/api/v1/_lib/one-pass-approval.js";
const key=Buffer.alloc(32,7).toString("base64");
test("development vault encrypts with user-bound associated data",async()=>{const vault=new DevelopmentIdentityVault({keyBase64:key}),value={passportNumber:"M12345678",legalSurname:"TEST"},envelope=await vault.storeEncryptedTravelerIdentity({userId:"user-a",recordId:"record-1",value});assert.doesNotMatch(envelope.ciphertext,/M12345678|TEST/);assert.deepEqual(await vault.retrieveForApprovedPurpose({userId:"user-a",recordId:"record-1",envelope}),value);await assert.rejects(()=>vault.retrieveForApprovedPurpose({userId:"user-b",recordId:"record-1",envelope}),/could not be unlocked/);});
test("development vault never runs in production and production vault fails closed",async()=>{assert.throws(()=>new DevelopmentIdentityVault({keyBase64:key,production:true}),/cannot run in production/);await assert.rejects(()=>new ProductionIdentityVault().storeEncryptedTravelerIdentity({}),/Managed KMS/);});
test("identity masking and field minimization exclude unapproved fields",()=>{const identity={passportNumber:"M12345678",legalSurname:"TEST",dateOfBirth:"2000-01-01",secret:"no"};assert.equal(revealMaskedIdentity(identity).passportNumberMasked,"•••••5678");assert.deepEqual(selectIdentityFields(identity,["legalSurname","secret"]),{legalSurname:"TEST"});});
test("passkey challenges reject expiration, replay, wrong purpose, origin and RP",()=>{const valid={challenge:"abc",purpose:"booking:1",expires_at:new Date(Date.now()+60000).toISOString(),consumed_at:null};assert.doesNotThrow(()=>assertChallenge(valid,{challenge:"abc",purpose:"booking:1"}));assert.throws(()=>assertChallenge({...valid,consumed_at:new Date().toISOString()},{challenge:"abc",purpose:"booking:1"}),/no longer valid/);assert.throws(()=>assertChallenge({...valid,expires_at:new Date(0).toISOString()},{challenge:"abc",purpose:"booking:1"}),/expired/);assert.throws(()=>assertChallenge(valid,{challenge:"abc",purpose:"booking:2"}),/does not match/);assert.throws(()=>assertWebAuthnContext({expectedOrigin:"https://preview.example",actualOrigin:"https://evil.example",expectedRpId:"preview.example",actualRpId:"preview.example"}),/origin/);});
test("ONE Pass production flags fail closed",()=>{assert.throws(()=>onePassConfig({APP_ENV:"production",ONE_PASS_ENABLED:"true",IDENTITY_VAULT_PROVIDER:"development"}),/Production Identity Vault/);assert.throws(()=>onePassConfig({APP_ENV:"production",ONE_PASS_ENABLED:"true",REAL_BOOKING_ENABLED:"true"}),/reauthentication/);});
test("mock providers are visibly demo and coordinator never executes without production providers",async()=>{const mock=new MockProviderAdapter({id:"fictional-flight"});assert.equal((await mock.execute({approved:true})).executed,false);const coordinator=new TransactionCoordinator({payment:mock,booking:mock});assert.deepEqual(await coordinator.execute({approval:{verified:true,reauthenticated:true},idempotencyKey:"abcdefghijklmnop"}),{state:"plan_created",executed:false,status:"provider_not_configured"});});
test("exact approval invalidates changed price and binds device confirmation",async()=>{const pkg=await createApprovalPackage({missionId:"m1",travelers:["self"],provider:"test-provider",items:["flight"],dates:{out:"2026-08-01"},price:100,currency:"USD",taxesAndFees:10,cancellationPolicy:"refundable",paymentMethodReference:"token-ref",identityFieldsShared:["legalSurname"],identityRecipient:"test-provider",expiresAt:new Date(Date.now()+60000).toISOString(),riskLevel:"high"});const approved={...pkg,status:"approved"};assert.doesNotThrow(()=>assertApprovalPackage(approved,{expectedHash:pkg.payloadHash,reauthentication:{verified:true,actionHash:pkg.payloadHash}}));const changed=await createApprovalPackage({...pkg,price:101});assert.notEqual(changed.payloadHash,pkg.payloadHash);assert.throws(()=>assertApprovalPackage(approved,{expectedHash:changed.payloadHash,reauthentication:{verified:true,actionHash:changed.payloadHash}}),/changed/);});
test("just-in-time identity release shares only approved fields",async()=>{const pkg=await createApprovalPackage({missionId:"m1",travelers:["self"],provider:"test-provider",items:["flight"],dates:{out:"2026-08-01"},price:100,currency:"USD",taxesAndFees:10,cancellationPolicy:"refundable",paymentMethodReference:"token-ref",identityFieldsShared:["legalSurname"],identityRecipient:"test-provider",expiresAt:new Date(Date.now()+60000).toISOString(),riskLevel:"high"}),approved={...pkg,status:"approved"};let received;const provider={executeApproved:async payload=>(received=structuredClone(payload),{status:"demo"})};await releaseIdentityJustInTime({identity:{legalSurname:"TEST",passportNumber:"M12345678"},approvalPackage:approved,reauthentication:{verified:true,actionHash:pkg.payloadHash},providerAdapter:provider});assert.deepEqual(received.identity,{legalSurname:"TEST"});assert.doesNotMatch(JSON.stringify(received),/M12345678/);});
test("ONE Pass migration enables RLS and blocks direct sensitive writes",async()=>{const sql=await readFile(new URL("../supabase/migrations/202607180001_one_pass.sql",import.meta.url),"utf8");for(const table of["one_passes","travel_preferences","identity_vault_records","loyalty_accounts","payment_method_references","passkey_credentials","approval_packages","booking_confirmations","itinerary_items","vault_access_events"])assert.match(sql,new RegExp(`alter table public\\.${table} enable row level security`));assert.match(sql,/revoke insert,update,delete on public\.identity_vault_records/);});
test("ONE Pass browser code does not collect provider passwords or sensitive identity",async()=>{const html=await readFile(new URL("../one-pass.html",import.meta.url),"utf8"),js=await readFile(new URL("../one-pass.js",import.meta.url),"utf8");assert.doesNotMatch(html,/name=["'](?:passport|card|cvv|provider_password)/i);assert.doesNotMatch(js,/localStorage.*passport|sessionStorage.*passport/i);});
test("ONE Pass API is protected by the shared rate limiter",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");assert.match(api,/rateLimit/);assert.match(api,/rateLimit\(context,\s*[""']one-pass[""'],\s*30\)/);});



test("ONE Pass UI supports English Korean and Spanish without mojibake", async () => {
  const html = await readFile(new URL("../one-pass.html", import.meta.url), "utf8");
  const js = await readFile(new URL("../one-pass.js", import.meta.url), "utf8");
  assert.doesNotMatch(html + js, /(?:â€¦|â€¢|í•|í”|ì•|ì„|ì—|ë¡|ë¯|�)/);
  assert.match(js, /ko:\s*\{/);
  assert.match(js, /es:\s*\{/);
  assert.match(js, /한 번만 설정하면/);
  assert.match(js, /Configúralo una vez/);
  assert.match(js, /SUPPORTED_LANGUAGES = \["en", "ko", "es"\]/);
});

test("ONE Pass frontend exposes privacy controls but no raw sensitive collection", async () => {
  const html = await readFile(new URL("../one-pass.html", import.meta.url), "utf8");
  assert.match(html, /Export ONE Pass data/);
  assert.match(html, /Delete Identity Pass/);
  assert.match(html, /Request ONE Pass deletion/);
  assert.doesNotMatch(html, /name=["'](?:passport|passport_number|card|card_number|cvv|provider_password|password)["']/i);
});


test("recent sensitive confirmations are exact, user-bound and single-use",()=>{const now=Date.now(),record={user_id:"user-a",challenge:"c1",purpose:"sensitive:export-one-pass",action_hash:"a".repeat(64),consumed_at:new Date(now-1000).toISOString(),completed_action_at:null,expires_at:new Date(now+60000).toISOString()};assert.doesNotThrow(()=>assertRecentSensitiveConfirmation(record,{userId:"user-a",challenge:"c1",purpose:"sensitive:export-one-pass",actionHash:"a".repeat(64),now}));assert.throws(()=>assertRecentSensitiveConfirmation({...record,consumed_at:null},{userId:"user-a",challenge:"c1",purpose:"sensitive:export-one-pass",actionHash:"a".repeat(64),now}),/not been completed/);assert.throws(()=>assertRecentSensitiveConfirmation(record,{userId:"user-b",challenge:"c1",purpose:"sensitive:export-one-pass",actionHash:"a".repeat(64),now}),/another user/);assert.throws(()=>assertRecentSensitiveConfirmation(record,{userId:"user-a",challenge:"c2",purpose:"sensitive:export-one-pass",actionHash:"a".repeat(64),now}),/does not match/);assert.throws(()=>assertRecentSensitiveConfirmation(record,{userId:"user-a",challenge:"c1",purpose:"sensitive:delete-one-pass",actionHash:"a".repeat(64),now}),/purpose/);assert.throws(()=>assertRecentSensitiveConfirmation(record,{userId:"user-a",challenge:"c1",purpose:"sensitive:export-one-pass",actionHash:"b".repeat(64),now}),/exact action/);assert.throws(()=>assertRecentSensitiveConfirmation({...record,completed_action_at:new Date(now).toISOString()},{userId:"user-a",challenge:"c1",purpose:"sensitive:export-one-pass",actionHash:"a".repeat(64),now}),/already been used/);assert.throws(()=>assertRecentSensitiveConfirmation({...record,consumed_at:new Date(now-11*60*1000).toISOString()},{userId:"user-a",challenge:"c1",purpose:"sensitive:export-one-pass",actionHash:"a".repeat(64),now}),/no longer recent/);});

test("ONE Pass sensitive privacy endpoints require recent device confirmation",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");assert.match(api,/sensitivePurpose=action=>/);assert.match(api,/assertSensitiveAction\(\{cfg,user,challenge:url\.searchParams\.get\("challenge"\),actionHash:url\.searchParams\.get\("actionHash"\),purpose:sensitivePurpose\("export-one-pass"\)/);assert.match(api,/purpose:sensitivePurpose\(`delete-identity-pass:\$\{id\}`\)/);assert.match(api,/sensitivePurpose\("delete-one-pass"\)/);assert.match(api,/one_pass_deletion_requested/);assert.match(api,/completed_action_at=is.null/);assert.ok(api.includes('passkey_challenges",{method:"PATCH",query:`id=eq.${record.id}&user_id=eq.${user.id}&completed_action_at=is.null`'));assert.match(api,/action_reauthentication_reused/);assert.match(api,/vault_record_id:id/);assert.doesNotMatch(api,/identity_vault_record_id|released_fields|request_id/);assert.match(api,/alreadyRequested:true/);assert.match(api,/vault_access_events/);});

test("ONE Pass privacy-action migration is owner-readable and server-writable",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608020001_one_pass_privacy_actions.sql",import.meta.url),"utf8");assert.match(sql,/create table if not exists public\.one_pass_deletion_requests/);assert.match(sql,/alter table public\.one_pass_deletion_requests enable row level security/);assert.match(sql,/auth\.uid\(\) = user_id/);assert.match(sql,/revoke insert,update,delete on public\.one_pass_deletion_requests from authenticated/);assert.match(sql,/alter table public\.one_passes add column if not exists deleted_at/);assert.match(sql,/alter table public\.passkey_challenges add column if not exists completed_action_at/);assert.match(sql,/create unique index if not exists one_pass_deletion_requests_one_open_idx/);assert.doesNotMatch(sql,/security definer/i);});


test("ONE Pass API ignores client-controlled user identifiers and never reads browser storage",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8"),js=await readFile(new URL("../one-pass.js",import.meta.url),"utf8");assert.match(api,/user=await currentUser\(request,cfg\)/);assert.doesNotMatch(api,/input\.user_id|input\.userId|headers\.get\(["\']x-user|localStorage|sessionStorage/);assert.doesNotMatch(js,/localStorage.*(?:passport|token|passkey|assertion|user_id)|sessionStorage.*(?:passport|token|passkey|assertion|user_id)/i);});

test("ONE Pass production cannot enable test bypass through HTTP",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8"),config=await readFile(new URL("../functions/api/v1/_lib/one-pass-config.js",import.meta.url),"utf8");assert.doesNotMatch(api,/x-test|bypass|devMode|mockVerified|skipVerification/i);assert.match(config,/APP_ENV/);assert.throws(()=>onePassConfig({APP_ENV:"production",ONE_PASS_ENABLED:"true",PASSKEY_REAUTH_ENABLED:"true"}),/Passkey RP ID|passkey verification/);assert.doesNotThrow(()=>onePassConfig({APP_ENV:"production",ONE_PASS_ENABLED:"true",PASSKEY_REAUTH_ENABLED:"true",WEBAUTHN_RP_ID:"one.example",WEBAUTHN_EXPECTED_ORIGINS:"https://one.example"}));});

test("ONE Pass audit and export code excludes sensitive plaintext",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");assert.match(api,/Full identity-vault plaintext is intentionally excluded/);const exportBlock=api.slice(api.indexOf('if(section==="export"'),api.indexOf('if(section==="passkeys"'));assert.doesNotMatch(exportBlock,/identity_vault_records|passport_number|passportNumber|ciphertext|nonce|public_key|access_token|session_token|provider_password/i);assert.match(api,/privacy_safe_reason/);assert.match(api,/privacy_safe_metadata|recent_device_confirmation/);});

test("WebAuthn verifier requires a real verification binding, not a string flag",async()=>{assert.equal(hasWebAuthnVerifier("configured"),false);assert.equal(hasWebAuthnVerifier({verify:async()=>({verified:true})}),true);await assert.rejects(()=>new WebAuthnVerifier("configured").verify({}),/not configured/);assert.deepEqual(await new WebAuthnVerifier({verify:async request=>({verified:true,echo:request.expectedRpId})}).verify({allowInjectedVerifier:true,expectedRpId:"one.example"}),{verified:true,echo:"one.example"});});

test("ONE Pass API exposes standards-shaped registration and authentication option flows",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");assert.match(api,/registrationOptions/);assert.match(api,/pubKeyCredParams/);assert.match(api,/authenticatorSelection:\{residentKey:"preferred",userVerification:"required"\}/);assert.match(api,/authenticationOptions/);assert.match(api,/allowCredentials:credentials\.map\(publicCredentialDescriptor\)/);assert.match(api,/userVerification:"required"/);assert.match(api,/parseSensitivePurpose/);assert.match(api,/actionHash=await sensitiveActionHash\(user,parsed\.action,parsed\.extra\)/);});

test("ONE Pass passkey verification checks registered owner credential and updates usage",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");assert.match(api,/credential_not_allowed/);assert.match(api,/credential_id=eq\.\$\{encodeURIComponent\(credentialId\)\}&user_id=eq\.\$\{user\.id\}&revoked_at=is\.null/);assert.match(api,/last_used_at:new Date\(\)\.toISOString\(\)/);assert.match(api,/sign_count:nextSignCount/);assert.match(api,/passkey_renamed/);assert.match(api,/passkey_revoked/);});

test("ONE Pass frontend performs real browser ceremony and has no insecure privacy fallback",async()=>{const html=await readFile(new URL("../one-pass.html",import.meta.url),"utf8"),js=await readFile(new URL("../one-pass.js",import.meta.url),"utf8");assert.match(html,/id="exportPass" type="button" disabled/);assert.doesNotMatch(html,/href="\/api\/v1\/one-pass\/export"/);assert.match(js,/navigator\.credentials\.create/);assert.match(js,/navigator\.credentials\.get/);assert.match(js,/serializeCredential/);assert.match(js,/confirmWithPasskey/);assert.match(js,/passkeyConfigured/);assert.match(js,/copy\("unavailable"\)/);assert.doesNotMatch(js,/mockVerified|skipVerification|confirm\([^)]*Face ID|fingerprint succeeded/i);});

test("ONE Pass export downloads structured JSON after server confirmation",async()=>{const js=await readFile(new URL("../one-pass.js",import.meta.url),"utf8"),api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");assert.match(js,/new Blob\(\[JSON\.stringify\(\{ schemaVersion: 1, \.\.\.data \}/);assert.match(js,/kastiz-one-pass-export-/);assert.match(api,/schemaVersion:1,exportedAt/);assert.doesNotMatch(api,/identity_vault_records.*select=\*/);});

test("Full ONE Pass deletion records a request and does not immediately claim completion",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");const block=api.slice(api.indexOf('if(!section&&request.method==="DELETE")'),api.indexOf('if(section==="create"'));assert.match(block,/request_type:"one_pass",status:"requested"/);assert.match(block,/pending_processing:true/);assert.match(block,/alreadyRequested:true/);assert.doesNotMatch(block,/one_passes",\{method:"PATCH"|identity_vault_records",\{method:"PATCH"|status:"deleted"/);});

test("ONE Pass local database instructions are honest when Supabase config is absent",async()=>{const doc=await readFile(new URL("../docs/ONE_PASS_LOCAL_SUPABASE_SETUP.md",import.meta.url),"utf8");assert.match(doc,/supabase\/config\.toml/);assert.match(doc,/has not been applied/);assert.match(doc,/Do not paste Supabase service keys/);assert.match(doc,/cannot truthfully claim/);});

test("ONE Pass real WebAuthn verifier dependency is installed and used by default",async()=>{assert.equal(hasSimpleWebAuthnServer,true);const verifier=new SimpleWebAuthnServerVerifier();await assert.rejects(()=>verifier.verifyRegistration({payload:{id:"bad",rawId:"bad",type:"public-key",response:{clientDataJSON:"bad",attestationObject:"bad"},clientExtensionResults:{}},expectedChallenge:"challenge",expectedOrigins:["http://localhost:8770"],expectedRpId:"localhost"}),/could not be verified/);await assert.rejects(()=>new WebAuthnVerifier({verify:async()=>({verified:true})}).verify({kind:"authentication",payload:{id:"bad"},credential:{credential_id:"bad",public_key:"bad",sign_count:0},expectedChallenge:"challenge",expectedOrigins:["http://localhost:8770"],expectedRpId:"localhost"}),/failed|could not|confirmation/);});

test("ONE Pass RP and origin configuration rejects unsafe production values",()=>{assert.doesNotThrow(()=>validateRpAndOrigins({rpId:"localhost",expectedOrigins:["http://localhost:8770"],production:false}));assert.doesNotThrow(()=>validateRpAndOrigins({rpId:"staging.kastiz.com",expectedOrigins:["https://staging.kastiz.com"],production:true}));assert.throws(()=>validateRpAndOrigins({rpId:"*.kastiz.com",expectedOrigins:["https://kastiz.com"],production:true}),/RP ID/);assert.throws(()=>validateRpAndOrigins({rpId:"kastiz.com",expectedOrigins:["https://*.kastiz.com"],production:true}),/Wildcard/);assert.throws(()=>validateRpAndOrigins({rpId:"localhost",expectedOrigins:["https://kastiz.com"],production:true}),/localhost/);assert.throws(()=>validateRpAndOrigins({rpId:"kastiz.com",expectedOrigins:["http://kastiz.com"],production:true}),/HTTPS/);});

test("ONE Pass WebAuthn options are generated by SimpleWebAuthn with required verification",async()=>{const flags={rpId:"localhost",rpName:"Kastiz ONE Local",expectedOrigins:["http://localhost:8770"],challengeTtl:300,production:false};const user={id:"11111111-1111-4111-8111-111111111111",email:"user@example.test",user_metadata:{display_name:"User A"}};const reg=await createRegistrationOptions({flags,user,challenge:"registration-challenge",existingCredentials:[{credential_id:"existing",transports:["internal"]}]});assert.equal(reg.rp.id,"localhost");assert.match(reg.challenge,/^[A-Za-z0-9_-]+$/);assert.equal(reg.authenticatorSelection.userVerification,"required");assert.deepEqual(reg.supportedAlgorithmIDs||reg.pubKeyCredParams?.map(item=>item.alg).filter(Boolean),reg.supportedAlgorithmIDs||[-7,-257]);assert.ok(reg.excludeCredentials?.length>=1);const auth=await createAuthenticationOptions({flags,challenge:"authentication-challenge",credentials:[{credential_id:"existing",transports:["internal"]}]});assert.equal(auth.rpId,"localhost");assert.match(auth.challenge,/^[A-Za-z0-9_-]+$/);assert.equal(auth.userVerification,"required");assert.equal(auth.allowCredentials[0].id,"existing");});

test("ONE Pass API verifies authentication with stored public key before consuming challenge",async()=>{const api=await readFile(new URL("../functions/api/v1/one-pass/[[path]].js",import.meta.url),"utf8");assert.match(api,/credential_id=eq\.\$\{encodeURIComponent\(credentialId\)\}&user_id=eq\.\$\{user\.id\}&revoked_at=is\.null&select=id,credential_id,public_key,sign_count/);assert.match(api,/kind:"authentication"/);assert.match(api,/expectedOrigins:record\.expected_origins\|\|flags\.expectedOrigins/);assert.match(api,/consumed=one\(await trustedDb\(cfg,"passkey_challenges"/);assert.match(api,/if\(!consumed\)throw new ApiError\(409,"challenge_replayed"/);assert.doesNotMatch(api,/new WebAuthnVerifier\(context\.env\.WEBAUTHN_VERIFIER\)/);});

test("ONE Pass local Supabase config and WebAuthn metadata migration are safe and reproducible",async()=>{const config=await readFile(new URL("../supabase/config.toml",import.meta.url),"utf8"),migration=await readFile(new URL("../supabase/migrations/202608020002_one_pass_webauthn_metadata.sql",import.meta.url),"utf8"),env=await readFile(new URL("../.env.example",import.meta.url),"utf8"),gitignore=await readFile(new URL("../.gitignore",import.meta.url),"utf8");assert.match(config,/project_id = "kastiz-one-local"/);assert.match(config,/site_url = "http:\/\/localhost:8770"/);assert.match(migration,/alter table public\.passkey_credentials add column if not exists credential_device_type/);assert.match(migration,/alter table public\.passkey_challenges add column if not exists expected_origins text\[\]/);assert.match(migration,/revoke all on public\.passkey_challenges from anon/);assert.doesNotMatch(config+env,/eyJ|sk-/i);assert.match(env,/SUPABASE_SERVICE_ROLE_KEY=\r?\n/);assert.match(env,/WEBAUTHN_EXPECTED_ORIGINS=http:\/\/localhost:8770,http:\/\/127\.0\.0\.1:8770/);assert.match(env,/CBOR_NATIVE_ACCELERATION_DISABLED=true/);assert.match(gitignore,/supabase\/\.temp\//);});