-- Architecture-only Mission Economy V1. No payment or subscription provider is connected.
create table public.subscription_accounts(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id) on delete cascade,tier_key text not null default 'free',status text not null default 'architecture_only' check(status in('architecture_only','inactive','future_active')),configuration jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(owner_user_id));
create table public.mission_wallets(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id) on delete cascade,wallet_type text not null check(wallet_type in('personal','family','group','business','enterprise')),monthly_balance integer not null default 0 check(monthly_balance>=0),purchased_balance integer not null default 0 check(purchased_balance>=0),bonus_balance integer not null default 0 check(bonus_balance>=0),promotional_balance integer not null default 0 check(promotional_balance>=0),monthly_allocation integer not null default 0 check(monthly_allocation>=0),expiration_rules jsonb not null default '{}',version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.mission_coin_ledger(id uuid primary key default gen_random_uuid(),wallet_id uuid not null references public.mission_wallets(id) on delete cascade,mission_id uuid references public.missions(id) on delete set null,event_type text not null check(event_type in('monthly_allocation','coins_added','free_action','mission_completed','expired','future_transfer','future_gift')),coin_delta integer not null,source text,completion_reference text,period_key text,expires_at timestamptz,safe_metadata jsonb not null default '{}',created_at timestamptz not null default now());
create unique index mission_coin_once_per_completed_mission on public.mission_coin_ledger(wallet_id,mission_id) where event_type='mission_completed';
create unique index mission_coin_completion_reference_unique on public.mission_coin_ledger(wallet_id,completion_reference) where completion_reference is not null;
create table public.mission_workspaces(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references auth.users(id) on delete cascade,wallet_id uuid not null references public.mission_wallets(id) on delete restrict,workspace_type text not null check(workspace_type in('family','group','business','enterprise')),name text not null check(char_length(name)<=120),configuration jsonb not null default '{}',created_at timestamptz not null default now());
create table public.mission_workspace_members(workspace_id uuid not null references public.mission_workspaces(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role_key text not null check(role_key in('owner','administrator','parent','adult_member','child','employee','manager','guest','viewer')),permissions_override jsonb not null default '{}',created_at timestamptz not null default now(),primary key(workspace_id,user_id));
create table public.mission_departments(id uuid primary key default gen_random_uuid(),workspace_id uuid not null references public.mission_workspaces(id) on delete cascade,parent_department_id uuid references public.mission_departments(id) on delete set null,name text not null check(char_length(name)<=120),created_at timestamptz not null default now());
create table public.subscription_feature_flags(id uuid primary key default gen_random_uuid(),tier_key text not null,feature_key text not null,enabled boolean not null default false,configuration jsonb not null default '{}',updated_at timestamptz not null default now(),unique(tier_key,feature_key));

alter table public.subscription_accounts enable row level security;alter table public.mission_wallets enable row level security;alter table public.mission_coin_ledger enable row level security;alter table public.mission_workspaces enable row level security;alter table public.mission_workspace_members enable row level security;alter table public.mission_departments enable row level security;alter table public.subscription_feature_flags enable row level security;
create policy subscription_owner_read on public.subscription_accounts for select using(owner_user_id=auth.uid());
create policy wallet_owner_read on public.mission_wallets for select using(owner_user_id=auth.uid());
create policy ledger_owner_read on public.mission_coin_ledger for select using(exists(select 1 from public.mission_wallets w where w.id=wallet_id and w.owner_user_id=auth.uid()));
create policy workspace_owner_read on public.mission_workspaces for select using(owner_user_id=auth.uid());
create policy member_self_read on public.mission_workspace_members for select using(user_id=auth.uid() or exists(select 1 from public.mission_workspaces w where w.id=workspace_id and w.owner_user_id=auth.uid()));
create policy department_member_read on public.mission_departments for select using(exists(select 1 from public.mission_workspaces w left join public.mission_workspace_members m on m.workspace_id=w.id where w.id=workspace_id and(w.owner_user_id=auth.uid() or m.user_id=auth.uid())));
revoke insert,update,delete on public.subscription_accounts,public.mission_wallets,public.mission_coin_ledger,public.mission_workspaces,public.mission_workspace_members,public.mission_departments,public.subscription_feature_flags from authenticated;
grant select on public.subscription_accounts,public.mission_wallets,public.mission_coin_ledger,public.mission_workspaces,public.mission_workspace_members,public.mission_departments to authenticated;
