-- ONE Intelligence Layer V1: derived, consent-scoped patterns only. No external integrations or execution.
create table if not exists public.intelligence_patterns(id uuid primary key default gen_random_uuid(),account_id uuid not null references auth.users(id) on delete cascade,workspace_id uuid references public.mission_workspaces(id) on delete cascade,pattern_type text not null,category text not null,confidence numeric(4,3) not null check(confidence between 0 and 1),evidence_count integer not null default 1 check(evidence_count>0),positive_feedback_count integer not null default 0,negative_feedback_count integer not null default 0,last_used_at timestamptz,last_confirmed_at timestamptz,expiration_at timestamptz,consent_scope text not null,data_source text not null,status text not null default 'ACTIVE',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.one_suggestions(id uuid primary key default gen_random_uuid(),account_id uuid not null references auth.users(id) on delete cascade,workspace_id uuid references public.mission_workspaces(id) on delete cascade,suggestion_type text not null,category text not null,confidence_band text not null check(confidence_band in('LOW','MEDIUM','HIGH')),source_state text not null check(source_state in('LIVE','ESTIMATED','DEMO','UNAVAILABLE')),related_mission_id uuid references public.missions(id) on delete set null,privacy_classification text not null,status text not null,expires_at timestamptz,created_at timestamptz not null default now(),safe_metadata jsonb not null default '{}');
create table if not exists public.suggestion_feedback(id uuid primary key default gen_random_uuid(),suggestion_id uuid not null references public.one_suggestions(id) on delete cascade,account_id uuid not null references auth.users(id) on delete cascade,action text not null check(action in('ACCEPTED','DISMISSED','IGNORED','EDITED','COMPLETED','REOPENED')),category text not null,confidence_band text not null,created_at timestamptz not null default now());
create table if not exists public.intelligence_settings(account_id uuid primary key references auth.users(id) on delete cascade,settings jsonb not null default '{"enabled":true,"frequency":"BALANCED","learningPaused":false}',updated_at timestamptz not null default now());
alter table public.intelligence_patterns enable row level security;alter table public.one_suggestions enable row level security;alter table public.suggestion_feedback enable row level security;alter table public.intelligence_settings enable row level security;
create policy intelligence_pattern_owner_read on public.intelligence_patterns for select using(account_id=auth.uid());
create policy suggestion_owner_read on public.one_suggestions for select using(account_id=auth.uid());
create policy suggestion_feedback_owner_read on public.suggestion_feedback for select using(account_id=auth.uid());
create policy intelligence_settings_owner_read on public.intelligence_settings for select using(account_id=auth.uid());
revoke insert,update,delete on public.intelligence_patterns,public.one_suggestions,public.suggestion_feedback,public.intelligence_settings from authenticated;
grant select on public.intelligence_patterns,public.one_suggestions,public.suggestion_feedback,public.intelligence_settings to authenticated;
